%YAML:1.0

#common parameters
imu_topic: "/imu9250"
image_topic: "/camera/image"
output_path: "~/output"

#camera calibration 
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 320
image_height: 256
projection_parameters:
   k2: 0.00678170986454365
   k3: -0.09656039601043327
   k4: 0.030048510267337486
   k5: -0.21070557110703453
   mu: 105.1591140381833
   mv: 105.10018663121393
   u0: 160.3036237349531
   v0: 124.8890403122616

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.02665549,  0.0088856,   0.99960519 ,
          -0.99785277, -0.06008292, -0.02607468, 
          0.05982751, -0.99815384,  0.01046806]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.04238352,-0.01804016, 0.04310278 ]

#feature traker paprameters
max_cnt: 300           # max feature number in feature tracking
min_dist: 12           # min distance between two features 
freq: 20               # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, turn on equalize to find enough features
fisheye: 1              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.7950798194785288e-01  #7.84e-01 #3.9276194479831016e-01     # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 2.4289620711139218e-02   #2.48e-02 #1.2404717718073521e-02        # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 6.6477919521353089e-03  #3.35e-02 #1.6760765091147032e-02      # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 3.9957639083624844e-04   #10.4e-04  #5.6948896954023307e-04      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1             # useful in real-time and large project
pose_graph_save_path: "/home/ubuntu/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.008690234777500675             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
